### ISSUE TITLE
Strange java process

### ISSUE THREAD

**Issue by l15k4** [implydata/distribution-docker#1]
Hey,

I did : 

```
FROM imply/imply

RUN sed -i 's/-Xmx256m/-Xmx1024m/g' conf-quickstart/druid/overlord/jvm.config
RUN sed -i 's/-Xmx64m/-Xmx192m/g' conf-quickstart/druid/middleManager/jvm.config
RUN sed -i 's/-Xmx1g/-Xmx2g/g' conf-quickstart/druid/historical/jvm.config
RUN sed -i 's/-XX:MaxDirectMemorySize=1280m/-XX:MaxDirectMemorySize=2g/g' conf-quickstart/druid/historical/jvm.config
RUN sed -i 's/-Xmx256m/-Xmx512m/g' conf-quickstart/druid/coordinator/jvm.config
```

to easily identify the java processes when monitoring Druid, but there is still one Java process that consumes 100% cpu and I cannot figure our what it is : 
https://gist.github.com/l15k4/dec37602d6a1f2311389

What happens is that I'm indexing into druid and all processes are basically idling except of this one and I cannot increase its resources... I cannot find where it is started in https://github.com/implydata/distribution

My guess is that it's a hadoop task that is created by middle manager, in that case I didn't know that it's being created as a new java process, hence all this ^^ xmx bump is useless :-)

Still, I would expect the process to look according to : 

```
druid.indexer.runner.javaOpts=-server -Xmx2g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
```

But these JAVA_OPTS are missing, so it operates with minimum Heap size... WDYT ?

**Comment by gianm** [comment]
Hey @l15k4, that is very likely a task peon corresponding to the task you're running. It's hard to tell because the ps output is cut off; the classpath is so long that you can't actually see the rest of the command line. It probably actually is using the correct JAVA_OPTS though. You could confirm what it's doing by using `jmap` and `jstack` on that process.

Classpaths should be shorter in the next Imply release, so it'll be easier to see everything in the ps output after that.

**Comment by l15k4** [comment]
Here it's complete http://pastebin.com/raw/8xRLtqET

Yeah, it is the peon but it is not given the `JAVA_OPTS` so it is GC choked due to minimum Heap it gets ...
I was chasing indexing performance for a long time and I think I finally got it :-)

**Comment by gianm** [comment]
You actually can't see the full command-line in ps, since Linux truncates it to 4096 bytes by default. (yours is exactly 4096 bytes, and looks like it's cut off in the middle of the classpath, so you tell it's truncated). But `jmap -heap` should be able to confirm whether or not it's actually getting the correct heap size.

**Comment by l15k4** [comment]
Ah, sorry, the task ended just before I make it :-) I copied wrong process...

Anyway if there was JAVA_OPT it would be before `-cp` ... after which there should be only classpath and Main class name ...

I cannot do `jmap` on a process running in docker container, neither from host nor from guest : 

http://pastebin.com/w2zRpSJ3

**Comment by l15k4** [comment]
Bad news for me, I think the `JAVA_OPT` is really cut off ... I started it outside docker container and posted a task, this is the jmap output with `Xmx=2g` : 

```
   MaxHeapSize              = 2147483648 (2048.0MB)
```

I'm not sure whether I should focus on tuning the distribution, indexing tasks or druid configuration...

Because I'm able to index only 300M events, ~ 16k events/s by hadoop indexing task https://gist.github.com/l15k4/b8948058356aab1c90ed ... 1 billion fails on Zookeeper timeout eventually ... resources don't seem to be a problem, I have 8 dimensions with low cardinality values and there is one HLL metric with 50% cardinality... Segment size is OK....

I can try to submit multiple tasks in parallel because 1Billion events big tasks is imho not a good practice... But still, 16k events/s performance is kinda slow, is it expected??? I was expecting smth like 80k events/s on a single server. Otherwise indexing billions take ages...

**Comment by gianm** [comment]
@l15k4, you should definitely see better performance locally if you split your task up into a few smaller tasks. You should also better performance if you use a real hadoop cluster rather than running in local mode. The batch tasks are not really optimized for running in local mode and likely does some sub-optimal things.

If streaming ingest works for you, that should also perform much better.

**Comment by l15k4** [comment]
Thank you @gianm I think it would be wiser if `intervals` in indexing task would split the job implicitly to `intervals.size` # of tasks. Instead of leaving this responsibility to api users... `intervals` being Array is very missleading, what is the difference between : 

```
[ "2010/2011", "2011/2012" ]
```

and

```
[ "2010/2012" ]
```

?

**Comment by gianm** [comment]
There isn't really any difference, the reason it's an array is actually so you can provide disjoint intervals like `["2010/2011", "2013/2014"]`.

I agree it would be better for the indexing task to split things up automatically! The only real reason it doesn't is that most of the dev effort so far has been put into the two most commonly used ingestion methods in production: remote hadoop clusters and streaming ingest (as opposed to local batch ingest which is generally not used by folks in production).

**Comment by l15k4** [comment]
Perfect !!! All is crystal clear now...

I will split one month (1 billion events) into 30 "daily" indexing tasks, having `# of cores` tasks run in parallel and it should be it. Thanks a lot for patience with me !!!

**Comment by gianm** [comment]
No worries :)

**Comment by l15k4** [comment]
Hey,

all worked out on this distribution except for one thing. Everytime I submit a parallel task (when one is already running) I immediately get `400 HTTP/1.1 400 Bad Request` response, even though the task is actually accepted and succeeds...

I'm using a quad-core so there are 8 virtual cores available and I use only parallelism=2 ... So overall it works, but it is really hard to defend against the `400 HTTP/1.1 400 Bad Request` response... I haven't found anything in logs...

**Comment by l15k4** [comment]
I solved it by `Thread.sleep(2000)` between the parallel tasks submissions...
