### ISSUE TITLE
Root directory name should not contain version

### ISSUE THREAD

**Issue by l15k4** [implydata/distribution-docker#2]
Hey,

I think that it would be wise having the distribution in a directory called just `imply` instead of : 

```
/root/imply-1.0.2
```

Because people will do bind-mounts : 

```
-v /var/data/druid/var:/root/imply-1.0.2/var
```

and if the version changes to `1.1.0` they will loose data on pull & restart

**Comment by gianm** [comment]
I changed the Dockerfile to use the layout:

- install in /opt/imply-x.y.z
- symlink /opt/imply -> /opt/imply-x.y.z so you can use /opt/imply as a fixed string
- store all runtime data in /mnt/imply so you can bind-mount this if you want to use an external volume for runtime data
